<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\News;
use \BNETDocs\Models\News\Create as CreateModel;
$title = 'Create News Post';
$description = 'This page enables a user to create news posts on the site.';
$url = '/news/create';
$error = $this->getContext()->error;
switch ($error)
{
  case CreateModel::ERROR_ACL_NOT_SET: $message = 'You do not have the privilege to create news posts.'; break;
  case CreateModel::ERROR_EMPTY_TITLE: $message = 'The title of the news post is required.'; break;
  case CreateModel::ERROR_EMPTY_CONTENT: $message = 'The content of the news post is required.'; break;
  case CreateModel::ERROR_NOT_LOGGED_IN: $message = 'You must be logged in to create news posts.'; break;
  case CreateModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Try again later.'; break;
  default: $message = $error;
}
$form_content = filter_var($this->getContext()->content, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$form_markdown = $this->getContext()->markdown;
$form_rss_exempt = $this->getContext()->rss_exempt;
$form_title = filter_var($this->getContext()->title, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$news_post_id = null;
$news_post_url = null;
require('./Includes/header.inc.phtml');
if (!$this->getContext()->acl_allowed) {
  echo '<div class="container">';
  require('./Includes/LoginRequired.inc.phtml');
  echo '</div>';
  require('./Includes/footer.inc.phtml');
  return;
} ?>
<div class="container">
  <h1><?=$title?></h1>
  <p><?=$description?></p>
<?  if ($error !== false) {
     if (!empty($message)) { ?>
  <div class="alert alert-danger">
    <p class="mb-0"><?=$message?></p>
  </div>
<?    }
      require('./News/Form.inc.phtml');
    } else { ?>
  <div class="alert alert-success">
    <p class="mb-0">Your news post has been created.</p>
  </div>
<?  } ?>
</div>
<? require('./Includes/footer.inc.phtml'); ?>
