<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\News;
use \BNETDocs\Models\News\Delete as DeleteModel;
$title = 'Delete News Post';
$description = 'This form allows an individual to delete a news post.';
$url = '/news/delete';
$error = $this->getContext()->error;
$id = $this->getContext()->id;
$news_post_title = $this->getContext()->title;
switch ($error)
{
  case DeleteModel::ERROR_ACL_NOT_SET: $message = 'You do not have the privilege to delete news posts.'; break;
  case DeleteModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Try again later.'; break;
  case DeleteModel::ERROR_NOT_FOUND: $message = 'Cannot find news post by that id.'; break;
  case DeleteModel::ERROR_NOT_LOGGED_IN: $message = 'You must be logged in to delete news posts.'; break;
  default: $message = $error;
}
require('./Includes/header.inc.phtml'); ?>
<div class="container">
<? if (!$this->getContext()->acl_allowed) { ?>
<? require('./Includes/LoginRequired.inc.phtml'); ?>
<? } else if (is_null($this->getContext()->error)) { ?>
  <h1 class="text-danger">Delete News Post</h1>
  <form method="POST" action="?id=<?=filter_var($id, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?>">
    <div class="form-group">
      <p class="text-danger">Are you sure you wish to delete this news post?</p>
      <div class="card text-light"><div class="card-body"><strong>Title:</strong> <?=filter_var($news_post_title, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></div></div>
    </div>
    <div class="form-group text-center">
      <a class="btn btn-primary" href="javascript:history.go(-1);" tabindex="1">Back</a>
      <input class="btn btn-danger" type="submit" value="Delete News Post" tabindex="2" autofocus="autofocus"/>
    </div>
  </form>
<? } else if ($this->getContext()->error === false) { ?>
  <h1 class="text-success">News Post Deleted</h1>
  <div class="alert alert-success">
    <p class="mb-0">You have successfully deleted the news post!</p>
  </div>
<? } else { ?>
  <div class="alert alert-danger">
    <p>An error occurred while attempting to delete the news post.</p>
    <p class="mb-0"><?=$message?></p>
  </div>
<? } ?>
</div>
<? require('./Includes/footer.inc.phtml'); ?>
