<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\News;
use \BNETDocs\Libraries\Comment;
use \BNETDocs\Models\News\Edit as EditModel;
$title = 'Edit News Post';
$description = 'This page enables a user to edit a news post on the site.';
$url = '/news/edit';
$_header_meta_properties = ['og:type' => 'article'];
$comments = $this->getContext()->comments;
$error = $this->getContext()->error;
switch ($error)
{
  case EditModel::ERROR_ACL_NOT_SET: $message = 'You do not have the privilege to edit news posts.'; break;
  case EditModel::ERROR_EMPTY_CONTENT: $message = 'The content of the news post is required.'; break;
  case EditModel::ERROR_EMPTY_TITLE: $message = 'The title of the news post is required.'; break;
  case EditModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Try again later.'; break;
  case EditModel::ERROR_NOT_FOUND: $message = 'Cannot find news post by that id.'; break;
  case EditModel::ERROR_NOT_LOGGED_IN: $message = 'You must be logged in to edit news posts.'; break;
  default: $message = $error;
}
$form_category = $this->getContext()->category;
$form_content = filter_var($this->getContext()->content, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$form_markdown = $this->getContext()->markdown;
$form_rss_exempt = $this->getContext()->rss_exempt;
$form_title = filter_var($this->getContext()->title, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
$news_categories = $this->getContext()->news_categories;
$news_post = $this->getContext()->news_post;
$news_post_id = filter_var($this->getContext()->news_post_id, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
require('./Includes/header.inc.phtml'); ?>
<div class="container">
<? if ($this->getContext()->acl_allowed) { ?>
  <h1><?=$title?></h1>
  <p><?=$description?></p>
<?  if ($error !== false) {
      if (!empty($message)) { ?>
  <div class="alert alert-danger">
    <p class="mb-0"><?=$message?></p>
  </div>
<?    }
      require('./News/Form.inc.phtml');
      $comment_parent_type = Comment::PARENT_TYPE_NEWS_POST; $comment_parent_id = $news_post_id; require('./Comment/Section.inc.phtml');
    } else { ?>
  <div class="alert alert-success">
    <p class="mb-0">Your news post has been edited successfully!</p>
  </div>
<?  }
  } else { require('./Includes/LoginRequired.inc.phtml'); } ?>
</div>
<? require('./Includes/footer.inc.phtml'); ?>
