<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\User;
use \BNETDocs\Libraries\Core\UrlFormatter;
use \BNETDocs\Models\User\ChangePassword as ChangePasswordModel;
$title = '🔑 Change Password';
$description = 'This form allows an individual to change the password to their account.';
$url = '/user/changepassword';
$active_user = $this->getContext()->active_user;
$error = $this->getContext()->error;
switch ($error)
{
  case ChangePasswordModel::ERROR_NOT_LOGGED_IN: $message = 'You must be logged in to change your password.'; break;
  case ChangePasswordModel::ERROR_NONMATCHING_PASSWORD: $message = 'The new password does not match its confirmation.'; break;
  case ChangePasswordModel::ERROR_PASSWORD_CONTAINS_EMAIL: $message = 'The password contains the email address, use a better password.'; break;
  case ChangePasswordModel::ERROR_PASSWORD_CONTAINS_USERNAME: $message = 'The password contains the username, use a better password.'; break;
  case ChangePasswordModel::ERROR_PASSWORD_INCORRECT: $message = 'You did not enter your correct current password.'; break;
  case ChangePasswordModel::ERROR_PASSWORD_TOO_LONG: $message = 'The password is too long, shorten it.'; break;
  case ChangePasswordModel::ERROR_PASSWORD_TOO_SHORT: $message = 'The password is too short, use a better password.'; break;
  case ChangePasswordModel::ERROR_PASSWORD_DENYLIST: $message = $this->getContext()->denylist_reason; if (empty($message)) $message = 'The new password is denylisted.'; break;
  case ChangePasswordModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Our staff have been notified of the issue. Try again later.'; break;
  default: $message = $error;
}
require('./Includes/header.inc.phtml'); ?>
<div class="container">
  <div class="card mx-auto mb-3" style="width:18rem;">
    <h4 class="card-header text-center"><?=$title?></h4>
    <div class="card-body">
<?  if ($error !== false) { ?>
<?    if (!empty($message)) { ?>
      <div class="alert alert-danger">
        <p class="mb-0"><?=$message?></p>
      </div>
<?    } ?>
<?    if (!$active_user) { ?>
      <a class="btn btn-success" href="<?=UrlFormatter::format('/user/login')?>" tabindex="1">Log in</a>
      <a class="btn btn-primary" href="<?=UrlFormatter::format('/user/resetpassword')?>" tabindex="2">Recover Password</a>
<?    } else { ?>
      <form method="POST" action="?">
        <div class="form-group">
          <label class="form-input-label" for="pw1">Current password:</label>
          <input class="form-control border border-secondary bg-dark text-light" type="password" name="pw1" id="pw1" tabindex="1" value="" required autofocus="autofocus"/>
        </div>
        <div class="form-group">
          <label class="form-input-label" for="pw2">New password:</label><br/>
          <input class="form-control border border-secondary bg-dark text-light" type="password" name="pw2" id="pw2" tabindex="2" value="" required/>
        </div>
        <div class="form-group">
          <label class="form-input-label"  for="pw3">Confirm password:</label><br/>
          <input class="form-control border border-secondary bg-dark text-light"  type="password" name="pw3" id="pw3" tabindex="3" value="" required/>
        </div>
        <div class="form-group text-center">
          <hr class="border-secondary w-25"/>
          <input class="btn btn-success" type="submit" value="Change Password" tabindex="4"/>
        </div>
      </form>
<?    } ?>
<?  } else { ?>
      <div class="alert alert-success">
        <h4 class="alert-header">Password Changed</h4>
        <p class="mb-0">You have successfully changed your password!</p>
      </div>
<?  } ?>
    </div>
  </div>
<? if ($active_user) { ?>
  <div class="text-center">
    <a class="btn btn-primary" href="<?=UrlFormatter::format('/user/update')?>"><img class="float-left" src="<?=UrlFormatter::assetify('svg/chevron-right-white.svg')?>"/> Return to Update Profile</a>
  </div>
<? } ?>
</div>
<? require('./Includes/footer.inc.phtml'); ?>
