<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Server;
use \BNETDocs\Libraries\Core\UrlFormatter;
use \BNETDocs\Models\Server\Delete as DeleteModel;
$title = 'Delete Server';
$description = 'This form allows an individual to delete a server.';
$url = '/server/delete';
$model = $this->getContext();
switch ($model->error)
{
  case DeleteModel::ERROR_ACL_NOT_SET: $message = 'You do not have the privilege to delete servers.'; break;
  case DeleteModel::ERROR_INTERNAL: $message = 'An internal error occurred while processing your request. Try again later.'; break;
  case DeleteModel::ERROR_NOT_FOUND: $message = 'Cannot find server by that id.'; break;
  case DeleteModel::ERROR_NOT_LOGGED_IN: $message = 'You must be logged in to delete servers.'; break;
  default: $message = $model->error;
}
$id = $model->server ? $model->server->getId() : null;
$json = $model->server ? json_encode($model->server, \BNETDocs\Views\Server\ViewJson::jsonFlags()) : null;
require('./Includes/header.inc.phtml');
echo '<div class="container">';
if ($model->error === DeleteModel::ERROR_ACL_NOT_SET)
{
  require('./Includes/LoginRequired.inc.phtml');
}
else if ($model->error === false)
{
  echo '<h1 class="text-success">Server Deleted</h1>';
  echo '<div class="alert alert-success"><p class="mb-0">The server has been deleted!</p></div>';
  echo '<div class="form-group text-center">';
  printf('<a class="btn btn-success" tabindex="1" href="%s">Server List</a> ', UrlFormatter::format('/servers'));
  echo '</div>';
}
else
{
  printf('<h1 class="text-danger">%s</h1>', $title);
  printf('<p class="text-danger">%s</p>', $description);
  if (!empty($message)) printf('<div class="alert alert-danger"><p class="mb-0">%s</p></div>', $message);
  if ($model->error !== DeleteModel::ERROR_NOT_FOUND)
  {
    printf('<form method="POST" action="?id=%d">', $id);
    echo '<div class="alert alert-danger"><p class="mb-0">Are you sure you wish to delete this server?</p></div>';
    if (!empty($json)) printf('<pre><code class="language-objectivec">%s</code></pre>', filter_var($json, FILTER_SANITIZE_FULL_SPECIAL_CHARS));
    echo '<a class="btn btn-primary" tabindex="1" href="javascript:history.go(-1);">Back</a> ';
    printf('<a class="btn btn-secondary" tabindex="2" href="%s">Server List</a> ', UrlFormatter::format('/servers'));
    echo '<input class="btn btn-danger" type="submit" value="Delete Server" tabindex="3" autofocus/>';
    echo '</form>';
  }
}
echo '</div>';
require('./Includes/footer.inc.phtml');
