<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Packet;
use \BNETDocs\Models\Packet\Delete as DeleteModel;
$title = 'Delete Packet';
$description = 'This form allows an individual to delete a packet.';
$url = '/packet/delete';
$error = $this->getContext()->error;
switch ($error)
{
  case DeleteModel::ERROR_ACL_NOT_SET: $message = 'You do not have the privilege to delete packets.'; break;
  case DeleteModel::ERROR_INTERNAL: $message = 'An internal error occurred. Try again later.'; break;
  case DeleteModel::ERROR_NOT_FOUND: $message = 'The requested packet does not exist or could not be found.'; break;
  case DeleteModel::ERROR_NOT_LOGGED_IN: $message = 'You must be logged in to delete packets.'; break;
  default: $message = $error;
}
$packet_id = filter_var($this->getContext()->packet_id, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
require('./Includes/header.inc.phtml'); ?>
<div class="container">
<? if (is_null($error)) { ?>
  <h1 class="text-danger"><?=$title?></h1>
  <p class="text-danger"><?=$description?></p>
  <form method="POST" action="?id=<?=$packet_id?>">
    <div class="alert alert-danger">
      <p class="mb-0">Are you sure you wish to delete this packet?</p>
    </div>
    <pre><code class="language-objectivec"><?=filter_var($this->getContext()->label, FILTER_SANITIZE_FULL_SPECIAL_CHARS)?></code></pre>
    <input class="btn btn-danger" type="submit" value="Delete Packet" tabindex="2" autofocus="autofocus"/>
  </form>
<? } else if ($error === false) { ?>
  <h1 class="text-success">Packet Deleted</h1>
  <div class="alert alert-success">
    <p class="mb-0">You have successfully deleted the packet!</p>
  </div>
<? } else { ?>
  <h1 class="text-danger">Delete Packet</h1>
  <div class="alert alert-danger">
    <p>An error occurred while attempting to delete the packet.</p>
    <p class="mb-0"><?=$message?></p>
  </div>
<? } ?>
</div>
<? require("./Includes/footer.inc.phtml"); ?>
