<?php /* vim: set colorcolumn= expandtab shiftwidth=2 softtabstop=2 tabstop=4 smarttab: */
namespace BNETDocs\Templates\Core;
use \BNETDocs\Libraries\Core\Config;
use \BNETDocs\Libraries\Core\UrlFormatter;
use \BNETDocs\Libraries\Core\VersionInfo; ?>
<!DOCTYPE html>
<html lang="en-US" class="h-100">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title>Internal Error &ndash; BNETDocs</title>
<link rel="stylesheet" href="<?=UrlFormatter::assetify('bootstrap-4.4.1-slate.min.css')?>" integrity="sha384-tfnMnZ6k273p3mDqSKikc9aXSvumltGq76Tbo+VMydpXeD5EDZwbQWo7nbZz+wc9" crossorigin="anonymous" />
<link rel="stylesheet" href="<?=UrlFormatter::assetify('datatables.min.css')?>" type="text/css" media="all" />
<link rel="stylesheet" href="<?=UrlFormatter::assetify('highlight/styles/vs2015.min.css')?>" type="text/css" media="all" />
<link rel="stylesheet" href="<?=UrlFormatter::assetify('footer.css')?>" type="text/css" media="all" />
<link rel="icon" href="<?=UrlFormatter::assetify('VSZX0bJ.png')?>" type="image/png" sizes="156x174" />
<script type="text/javascript" src="<?=UrlFormatter::assetify('BNETDocs.js')?>" async></script>
<link rel="alternate" href="/news.rss" type="application/rss+xml" title="BNETDocs News" />
<link rel="license" href="/legal" />
<meta name="keywords" content="battle.net,starcraft,warcraft,diablo,blizzard,logon sequences,packets,information,protocols,reference,programming,coding" />
<meta name="description" content="The requested resource does not exist or could not be found." />
<meta property="og:description" content="The requested resource does not exist or could not be found." />
<meta property="twitter:description" content="The requested resource does not exist or could not be found." />
<meta property="og:site_name" content="BNETDocs" />
<meta property="og:locale" content="en_US" />
<meta property="twitter:card" content="summary" />
<meta property="twitter:site" content="@BNETDocs" />
<meta property="og:title" content="Internal Error" />
<meta property="twitter:title" content="Internal Error" />
<meta property="og:image" content="/a/eNoi70A.png" />
<meta property="og:type" content="website" />
</head>
<body class="d-flex flex-column h-100">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
<a class="navbar-brand" style="color:#00ccad;" href="/welcome"><img class="float-left mr-2" src="<?=UrlFormatter::assetify('VSZX0bJ.png')?>" style="height:32px;" /> BNETDocs</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
<li class="nav-item"><a class="nav-link" href="/welcome">Welcome</a></li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarCommunityDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Community</a>
<div class="dropdown-menu" aria-labelledby="navbarCommunityDropdown">
<a class="dropdown-item" href="/discord">Discord</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="/credits">Contributors</a>
<a class="dropdown-item" href="/donate">Support Us</a>
<a class="dropdown-item" href="/servers">Server List</a>
<a class="dropdown-item" href="/user/index">Users</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="/privacy">Privacy Policy</a>
<a class="dropdown-item" href="/legal">Disclaimer &amp; TOS</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="https://files.bnetdocs.org/">File Archive</a>
<a class="dropdown-item" href="https://redux.bnetdocs.org/">BNETDocs Redux</a>
</div></li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarNewsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">News</a>
<div class="dropdown-menu" aria-labelledby="navbarNewsDropdown">
<a class="dropdown-item text-info" href="/news">All News</a>
</div></li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDocumentsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Documents</a>
<div class="dropdown-menu" aria-labelledby="navbarDocumentsDropdown">
<a class="dropdown-item text-info" href="/document/index">All Documents</a>
</div></li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarPacketsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Packets</a>
<div class="dropdown-menu" aria-labelledby="navbarPacketsDropdown">
<a class="dropdown-item text-info" href="/packet/index">All Packets</a>
</div></li>
</ul>
</div>
</nav>
<main class="mb-3">
<div class="container">
<div class="alert alert-danger" role="alert">
<h4 class="alert-heading">Internal Error</h4>
<p class="m-0">An internal server error occurred while processing the request.</p>
<p class="m-0">Please follow the <a rel="external" href="https://github.com/BNETDocs/bnetdocs-web/blob/phoenix/CONTRIBUTING.md">Contributing Guide</a> and <a rel="external" href="https://github.com/BNETDocs/bnetdocs-web/issues">report</a> this to us so it can be fixed.</p>
</div>
</div>
</main>
<footer class="footer mt-auto py-3">
<div class="container text-center">
<p class="small text-muted"><?=(VersionInfo::get()['bnetdocs'] ? sprintf('<a href="https://github.com/BNETDocs/bnetdocs-web/tree/%s" rel="external" title="Contribute to the BNETDocs source code!">BNETDocs %s</a> ', VersionInfo::get()['bnetdocs'][1], VersionInfo::get()['bnetdocs'][0]) : '(Development)')?> &copy; 2003-<?=date('Y')?> BNETDocs | <a href="/legal" title="BNETDocs Legal Page">Legal</a> | <a href="/privacy" title="BNETDocs Privacy Policy">Privacy Policy</a></p>
<p class="small text-muted">
BNETDocs is a documentation and discussion website for Blizzard Entertainment's
Battle.net&trade; and in-game protocols. You hereby acknowledge that BNETDocs
content is offered as is and without warranty. BNETDocs content may be
inaccurate as it is solely from third-party observations. BNETDocs is not
affiliated or partnered with Blizzard Entertainment in absolutely any way.
Battle.net&trade;, Starcraft&trade;, Warcraft&trade;, and Diablo&trade; are
trademarks or registered trademarks of Blizzard Entertainment, Inc., in the U.S.
and/or other countries.
</p>
</div>
</footer>
<?php if (Config::get('analytics.cloudflare')) { ?>
<!-- Cloudflare Web Analytics --><script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token":<?=json_encode(Config::get('analytics.cloudflare'))?>}'></script><!-- End Cloudflare Web Analytics -->
<?php } ?>
<script src="<?=UrlFormatter::assetify('jquery-3.7.0.slim.min.js')?>" type="text/javascript" integrity="sha384-w5y/xIeYixWvfM+A1cEbmHPURnvyqmVg5eVENruEdDjcyRLUSNej7512JQGspFUr" crossorigin="anonymous"></script>
<script src="<?=UrlFormatter::assetify('popper-1.16.0.min.js')?>" type="text/javascript" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="<?=UrlFormatter::assetify('bootstrap-4.4.1.min.js')?>" type="text/javascript" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="<?=UrlFormatter::assetify('datatables.min.js')?>" type="text/javascript" crossorigin="anonymous" charset="utf8"></script>
<script src="<?=UrlFormatter::assetify('highlight/highlight.min.js')?>" type="text/javascript" crossorigin="anonymous" charset="utf8"></script>
<script defer type="text/javascript">$(document).ready(function(){hljs.highlightAll()});</script>
<script src="<?=UrlFormatter::assetify('moment-2.29.4.min.js')?>" type="text/javascript" crossorigin="anonymous" charset="utf8"></script>
</body></html>
